/* SAVILLS PPM · Staffing Matrix seed — imported from
   "Staffing Matrix - Bandwidth Allocations v43 (JS 6.9.26).xlsx" · Data tab.
   255 person-to-project bandwidth allocations. Dates are calendar months
   (YYYY-MM), converted from the workbook's serial dates. Loaded once on first
   run to populate the localStorage staffing store; edits thereafter live in the
   store, not here. Re-import from the page overwrites with a fresh matrix. */
window.STAFF_SEED = [
{"proj":"Accenture PMO","status":"Active","type":"Awarded","client":"Accenture","person":"Brendan Hughes","start":"2026-02","end":"2026-12","pct":25,"note":""},
{"proj":"Accenture PMO","status":"Active","type":"Awarded","client":"Accenture","person":"Bailey Graves","start":"2026-02","end":"2026-12","pct":15,"note":""},
{"proj":"Athene","status":"Active","type":"Awarded","client":"Athene","person":"Eric Merkelson","start":"2025-09","end":"2026-06","pct":10,"note":"Toronto"},
{"proj":"Athene","status":"Active","type":"Awarded","client":"Athene","person":"Tasia Long","start":"2025-09","end":"2026-06","pct":10,"note":"Toronto"},
{"proj":"Baker McKenzie - CM","status":"Active","type":"Awarded","client":"Baker McKenzie","person":"Bailey Graves","start":"2026-03","end":"2026-06","pct":25,"note":""},
{"proj":"Baker McKenzie - CM","status":"Active","type":"Awarded","client":"Baker McKenzie","person":"Rachel Haberman","start":"2026-03","end":"2026-06","pct":25,"note":""},
{"proj":"BERS","status":"Active","type":"Awarded","client":"BERS","person":"Fred Buscaglia","start":"2026-04","end":"2026-12","pct":10,"note":""},
{"proj":"BERS","status":"Active","type":"Awarded","client":"BERS","person":"Jay Khoury","start":"2026-04","end":"2026-05","pct":30,"note":"Offboard Jay, onboard Ian W. from Fanatics 95M basement"},
{"proj":"BERS","status":"Active","type":"Awarded","client":"BERS","person":"Ian Wach","start":"2026-06","end":"2026-12","pct":30,"note":"Offboard Jay, onboard Ian W. from Fanatics 95M basement"},
{"proj":"Carlyle - 200P Refresh","status":"Active","type":"Awarded","client":"Carlyle","person":"Jay Khoury","start":"2026-01","end":"2026-07","pct":40,"note":"Is this still going on May/June/July?"},
{"proj":"Carlyle - 245 Park","status":"Active","type":"Awarded","client":"Carlyle","person":"Jason Bergen","start":"2026-05","end":"2027-05","pct":40,"note":""},
{"proj":"Carlyle - 245 Park","status":"Pursuit","type":"Opportunity","client":"Carlyle","person":"[NEW HIRE] Izzy Vollbrecht","start":"2026-07","end":"2027-05","pct":40,"note":"MG to weigh-in"},
{"proj":"Carlyle - 245 Park","status":"Pursuit","type":"Opportunity","client":"Carlyle","person":"Anika Tsapatsaris","start":"2026-08","end":"2027-05","pct":40,"note":"After completion of Fanatics FBG and/or JMAN?"},
{"proj":"Carlyle - 245 Park","status":"Active","type":"Awarded","client":"Carlyle","person":"Deb Greenfield","start":"2026-05","end":"2026-07","pct":20,"note":"Need long term solution for PM"},
{"proj":"Carlyle - 245 Park","status":"Pursuit","type":"Opportunity","client":"Carlyle","person":"Andrew Peters","start":"2026-08","end":"2026-09","pct":20,"note":"SD estimate"},
{"proj":"Carlyle - 245 Park","status":"Pursuit","type":"Opportunity","client":"Carlyle","person":"[NEW HIRE] Cost Manager","start":"2026-08","end":"2026-09","pct":20,"note":"SD estimate"},
{"proj":"Carlyle - LA","status":"Active","type":"Awarded","client":"Carlyle","person":"Jason Bergen","start":"2026-06","end":"2026-10","pct":20,"note":""},
{"proj":"Carlyle - LA","status":"Pursuit","type":"Opportunity","client":"Carlyle","person":"Alex He","start":"2026-07","end":"2026-10","pct":20,"note":"Need LA boots on ground light support"},
{"proj":"Carlyle - OVA Densification","status":"Pursuit","type":"Opportunity","client":"Carlyle","person":"Jason Bergen","start":"2026-05","end":"2026-08","pct":20,"note":"Need WA"},
{"proj":"Comcast CVSAs - 2026","status":"Active","type":"Awarded","client":"Comcast Corporation","person":"Jess White","start":"2026-01","end":"2026-12","pct":10,"note":""},
{"proj":"CCNY - Chelsea","status":"Active","type":"Awarded","client":"CCNY","person":"Marc Messina","start":"2025-11","end":"2026-12","pct":20,"note":""},
{"proj":"CCNY - Chelsea","status":"Active","type":"Awarded","client":"CCNY","person":"Joe Guarnieri","start":"2026-05","end":"2026-12","pct":50,"note":""},
{"proj":"CCNY - Chelsea","status":"Active","type":"Awarded","client":"CCNY","person":"Deb Greenfield","start":"2026-04","end":"2026-06","pct":25,"note":""},
{"proj":"Collibra NYC","status":"Active","type":"Awarded","client":"Collibra","person":"Fred Buscaglia","start":"2025-08","end":"2026-08","pct":10,"note":""},
{"proj":"Collibra NYC","status":"Active","type":"Awarded","client":"Collibra","person":"Victoria Verdan","start":"2026-01","end":"2026-08","pct":30,"note":""},
{"proj":"Convene - Terminal Warehouse (Mallory)","status":"Active","type":"Awarded","client":"Convene","person":"Fred Buscaglia","start":"2025-03","end":"2026-08","pct":10,"note":""},
{"proj":"Convene - Terminal Warehouse (Mallory)","status":"Active","type":"Awarded","client":"Convene","person":"Eric Merkelson","start":"2025-04","end":"2026-08","pct":10,"note":""},
{"proj":"Convene - Terminal Warehouse (Mallory)","status":"Active","type":"Awarded","client":"Convene","person":"Jonathan Stukalin","start":"2025-03","end":"2026-08","pct":60,"note":""},
{"proj":"Convene - Terminal Warehouse (Mallory)","status":"Active","type":"Awarded","client":"Convene","person":"Renee Becker","start":"2025-10","end":"2026-08","pct":50,"note":"Banner support"},
{"proj":"Convene - Miami (Cube)","status":"Active","type":"Awarded","client":"Convene","person":"Fred Buscaglia","start":"2025-11","end":"2026-12","pct":10,"note":""},
{"proj":"Convene - Miami (Cube)","status":"Active","type":"Awarded","client":"Convene","person":"Eric Merkelson","start":"2025-11","end":"2026-12","pct":35,"note":"Lease is at risk, the design team has been on pause but we/Savills have not officially been."},
{"proj":"Convene - Miami (Cube)","status":"Active","type":"Awarded","client":"Convene","person":"Chris Scala","start":"2025-11","end":"2026-12","pct":10,"note":""},
{"proj":"Convene - Miami (Cube)","status":"Active","type":"Awarded","client":"Convene","person":"Vicky Vidal","start":"2026-04","end":"2026-12","pct":10,"note":""},
{"proj":"Convene - Miami (Cube)","status":"Active","type":"Awarded","client":"Convene","person":"Beatriz dePaulis","start":"2026-01","end":"2026-12","pct":10,"note":""},
{"proj":"Convene - Aperture","status":"Active","type":"Awarded","client":"Convene","person":"Fred Buscaglia","start":"2026-04","end":"2026-12","pct":10,"note":""},
{"proj":"Convene - Aperture","status":"Active","type":"Awarded","client":"Convene","person":"Eric Merkelson","start":"2026-04","end":"2026-12","pct":50,"note":""},
{"proj":"Convene - Aperture","status":"Active","type":"Awarded","client":"Convene","person":"Ian Lee","start":"2026-04","end":"2026-12","pct":50,"note":""},
{"proj":"Convene - Aperture","status":"Active","type":"Awarded","client":"Convene","person":"Vicky Vidal","start":"2026-04","end":"2026-12","pct":50,"note":"APM or Izzy to free up Vicky to shift to MTSI incrementally beyond Alexandria HQ"},
{"proj":"Convene - Aperture","status":"Pursuit","type":"Opportunity","client":"Convene","person":"[NEW HIRE] APM","start":"2026-07","end":"2026-12","pct":50,"note":"APM or Izzy to free up Vicky to shift to MTSI"},
{"proj":"Convene - Neuhaus","status":"Active","type":"Awarded","client":"Convene","person":"Eric Merkelson","start":"2026-05","end":"2026-12","pct":10,"note":""},
{"proj":"Convene - Neuhaus","status":"Active","type":"Awarded","client":"Convene","person":"Ian Wach","start":"2026-05","end":"2026-12","pct":30,"note":""},
{"proj":"Convene - Neuhaus","status":"Active","type":"Awarded","client":"Convene","person":"[NEW HIRE] Alex Bluvol","start":"2026-07","end":"2026-12","pct":50,"note":""},
{"proj":"Dames","status":"Active","type":"Awarded","client":"Dames","person":"Kathryn Martinez","start":"2026-02","end":"2026-12","pct":10,"note":""},
{"proj":"Dames","status":"Active","type":"Awarded","client":"Dames","person":"Zac Sargent","start":"2026-06","end":"2026-12","pct":10,"note":""},
{"proj":"Disney - Hercules","status":"Active","type":"Awarded","client":"The Walt Disney Company","person":"Jessica Jeffrey","start":"2025-03","end":"2026-11","pct":5,"note":"Incremental support?"},
{"proj":"Earned","status":"Active","type":"Awarded","client":"Earned","person":"Alicia Cargo","start":"2026-03","end":"2026-09","pct":40,"note":""},
{"proj":"Earned","status":"Active","type":"Awarded","client":"Earned","person":"Maria Hadim","start":"2026-03","end":"2026-09","pct":25,"note":""},
{"proj":"EM Workplace 2025","status":"Active","type":"Awarded","client":"ExxonMobil","person":"Tonya Williams","start":"2025-01","end":"2026-01","pct":75,"note":""},
{"proj":"EM Site Surveys","status":"Active","type":"Awarded","client":"ExxonMobil","person":"Bailey Graves","start":"2026-06","end":"2026-07","pct":25,"note":""},
{"proj":"EM Site Surveys","status":"Active","type":"Awarded","client":"ExxonMobil","person":"Ariel Levin","start":"2026-06","end":"2026-07","pct":25,"note":""},
{"proj":"EM NALI","status":"Active","type":"Awarded","client":"ExxonMobil","person":"Tonya Williams","start":"2026-02","end":"2026-05","pct":30,"note":""},
{"proj":"EM NALI","status":"Active","type":"Awarded","client":"ExxonMobil","person":"kelly creighton","start":"2026-02","end":"2026-05","pct":50,"note":""},
{"proj":"EM NALI","status":"Active","type":"Awarded","client":"ExxonMobil","person":"Jess White","start":"2026-03","end":"2026-11","pct":50,"note":""},
{"proj":"EM NALI","status":"Active","type":"Awarded","client":"ExxonMobil","person":"Brendan Hughes","start":"2026-03","end":"2026-12","pct":25,"note":""},
{"proj":"EM NALI","status":"Active","type":"Awarded","client":"ExxonMobil","person":"Bailey Graves","start":"2026-02","end":"2026-04","pct":50,"note":""},
{"proj":"EM Residential","status":"Active","type":"Awarded","client":"ExxonMobil","person":"Tonya Williams","start":"2026-01","end":"2026-06","pct":25,"note":""},
{"proj":"EM Residential","status":"Active","type":"Awarded","client":"ExxonMobil","person":"Alli Hochberg","start":"2026-01","end":"2026-06","pct":50,"note":""},
{"proj":"Fanatics FBG NYC","status":"Active","type":"Awarded","client":"Fanatics","person":"Victoria Verdan","start":"2025-12","end":"2026-06","pct":30,"note":""},
{"proj":"Fanatics FBG NYC","status":"Active","type":"Awarded","client":"Fanatics","person":"Kristen Raymond","start":"2026-02","end":"2026-06","pct":10,"note":""},
{"proj":"Fanatics FBG NYC","status":"Active","type":"Awarded","client":"Fanatics","person":"Anika Tsapatsaris","start":"2026-02","end":"2026-06","pct":40,"note":""},
{"proj":"Fanatics FBG NYC","status":"Pursuit","type":"Opportunity","client":"Fanatics","person":"Victoria Verdan","start":"2026-07","end":"2026-07","pct":30,"note":""},
{"proj":"Fanatics FBG NYC","status":"Pursuit","type":"Opportunity","client":"Fanatics","person":"Kristen Raymond","start":"2026-07","end":"2026-07","pct":10,"note":""},
{"proj":"Fanatics FBG NYC","status":"Pursuit","type":"Opportunity","client":"Fanatics","person":"Anika Tsapatsaris","start":"2026-07","end":"2026-07","pct":40,"note":""},
{"proj":"Fanatics Portland","status":"Active","type":"Awarded","client":"Fanatics","person":"Anika Tsapatsaris","start":"2026-02","end":"2026-12","pct":50,"note":""},
{"proj":"Fanatics Portland","status":"Active","type":"Awarded","client":"Fanatics","person":"Alicia Cargo","start":"2026-02","end":"2026-12","pct":40,"note":"Ideally Rasam, if he comes back into the fold"},
{"proj":"Fanatics Portland","status":"Active","type":"Awarded","client":"Fanatics","person":"Kristen Raymond","start":"2025-10","end":"2026-12","pct":20,"note":""},
{"proj":"Fanatics Sunnyvale Tx","status":"Active","type":"Awarded","client":"Fanatics","person":"Alicia Cargo","start":"2026-04","end":"2026-12","pct":20,"note":""},
{"proj":"Fanatics Sunnyvale Tx","status":"Active","type":"Awarded","client":"Fanatics","person":"Anika Tsapatsaris","start":"2026-04","end":"2026-12","pct":20,"note":"Supported locally by Alyssa"},
{"proj":"Fanatics 95M Basement","status":"Active","type":"Awarded","client":"Fanatics","person":"Jason Bergen","start":"2026-03","end":"2026-12","pct":30,"note":""},
{"proj":"Fanatics 95M Basement","status":"Active","type":"Awarded","client":"Fanatics","person":"Ian Wach","start":"2026-05","end":"2026-06","pct":40,"note":"Transition CR workload to Renee B."},
{"proj":"Fanatics 95M Basement","status":"Active","type":"Awarded","client":"Fanatics","person":"Renee Becker","start":"2026-06","end":"2026-12","pct":40,"note":""},
{"proj":"Fanatics Miramar","status":"Active","type":"Awarded","client":"Fanatics","person":"ian Wach","start":"2026-03","end":"2026-09","pct":30,"note":""},
{"proj":"Fanatics Miramar","status":"Active","type":"Awarded","client":"Fanatics","person":"Beatriz dePaulis","start":"2026-08","end":"2026-09","pct":10,"note":""},
{"proj":"Fanatics Miramar","status":"Active","type":"Awarded","client":"Fanatics","person":"Joe Guarnieri","start":"2026-03","end":"2026-09","pct":35,"note":""},
{"proj":"Fanatics - PMO","status":"Active","type":"Awarded","client":"Fanatics","person":"Fred Buscaglia","start":"2025-05","end":"2026-12","pct":10,"note":""},
{"proj":"Fanatics - PMO","status":"Active","type":"Awarded","client":"Fanatics","person":"Kristen Raymond","start":"2025-05","end":"2026-12","pct":40,"note":"Potentially to be term for conv"},
{"proj":"Fanatics - PMO","status":"Active","type":"Awarded","client":"Fanatics","person":"Alicia Cargo","start":"2026-01","end":"2026-12","pct":15,"note":""},
{"proj":"Fanatics -  Staff Aug","status":"Active","type":"Awarded","client":"Fanatics","person":"Rasam Aminzadeh","start":"2026-05","end":"2026-12","pct":100,"note":"Likely to be insourced imminently"},
{"proj":"Fanatics Redwood City CA","status":"Active","type":"Awarded","client":"Fanatics","person":"Kristen Raymond","start":"2026-04","end":"2026-10","pct":25,"note":"Potential extension through EOY"},
{"proj":"Fanatics Redwood City CA","status":"Active","type":"Awarded","client":"Fanatics","person":"Ian Wach","start":"2026-05","end":"2026-10","pct":30,"note":"Potential extension through EOY"},
{"proj":"Fanatics Redwood City CA","status":"Active","type":"Awarded","client":"Fanatics","person":"Victoria Verdan","start":"2026-05","end":"2026-10","pct":30,"note":"Potential extension through EOY"},
{"proj":"Fanatics - Mitchell & Ness (Philly)","status":"Active","type":"Awarded","client":"Fanatics","person":"Kathryn Martinez","start":"2024-09","end":"2026-06","pct":20,"note":""},
{"proj":"Fanatics - Mitchell & Ness (Philly)","status":"Active","type":"Awarded","client":"Fanatics","person":"Tom Bucciaglia","start":"2024-09","end":"2026-06","pct":30,"note":""},
{"proj":"Fanatics - Mitchell & Ness (Philly)","status":"Active","type":"Awarded","client":"Fanatics","person":"Amanda Hirsh","start":"2026-02","end":"2026-06","pct":10,"note":""},
{"proj":"Foxy - Casabe House","status":"Active","type":"Awarded","client":"Foxy","person":"Liza Horstman","start":"2025-04","end":"2026-07","pct":10,"note":""},
{"proj":"Foxy - Casabe House","status":"Active","type":"Awarded","client":"Foxy","person":"Alex He","start":"2024-10","end":"2026-07","pct":10,"note":""},
{"proj":"Foxy / Selfhelp","status":"Active","type":"Awarded","client":"Foxy / Selfhelp","person":"Eno Chen","start":"2026-07","end":"2027-12","pct":10,"note":""},
{"proj":"Foxy / Selfhelp","status":"Active","type":"Awarded","client":"Foxy / Selfhelp","person":"Chris Scala","start":"2026-07","end":"2027-12","pct":5,"note":""},
{"proj":"GT WDC","status":"Pursuit","type":"Opportunity","client":"Greenberg Traurig","person":"[NEW HIRE] Izzy Vollbrecht","start":"2026-07","end":"2027-02","pct":25,"note":"Pending Ian's potential leave?"},
{"proj":"GT WDC","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Ian Lee","start":"2026-04","end":"2027-02","pct":25,"note":""},
{"proj":"GT WDC","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Rebekah Palmer","start":"2026-04","end":"2027-02","pct":25,"note":""},
{"proj":"GT WDC","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Naida Serak","start":"2026-04","end":"2027-02","pct":10,"note":""},
{"proj":"GT Garden City","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Ian Lee","start":"2026-02","end":"2027-04","pct":35,"note":""},
{"proj":"GT Garden City","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Eric Merkelson","start":"2026-02","end":"2027-04","pct":20,"note":""},
{"proj":"GT Boston","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Zac Sargent","start":"2025-09","end":"2027-12","pct":30,"note":""},
{"proj":"GT Boston","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Jess White","start":"2026-04","end":"2026-07","pct":20,"note":""},
{"proj":"GT Boston","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"[NEW HIRE] APM","start":"2026-07","end":"2027-12","pct":20,"note":"Naida to allocate APM optimally within GT account"},
{"proj":"GT Dallas","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Naida Serak","start":"2025-08","end":"2027-03","pct":25,"note":""},
{"proj":"GT Dallas","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Dannah Seecoomar","start":"2025-08","end":"2027-03","pct":25,"note":"Jennylee to GT Dallas to free up Dannah for Change Mgmt"},
{"proj":"GT Dallas","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Jennylee Nguyen","start":"2026-06","end":"2027-03","pct":25,"note":"Jennylee to GT Dallas to free up Dannah for Change Mgmt"},
{"proj":"GT Atlanta","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Michael McLane","start":"2025-08","end":"2027-09","pct":10,"note":""},
{"proj":"GT Atlanta","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Rebekah Palmer","start":"2025-08","end":"2027-09","pct":50,"note":""},
{"proj":"GT Atlanta","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Dannah Seecoomar","start":"2025-08","end":"2027-09","pct":40,"note":""},
{"proj":"GT West Palm Beach","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Michael McLane","start":"2026-06","end":"2027-02","pct":10,"note":""},
{"proj":"GT West Palm Beach","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Zac Sargent","start":"2026-06","end":"2027-02","pct":20,"note":""},
{"proj":"GT West Palm Beach","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Luke Borden","start":"2026-04","end":"2027-02","pct":20,"note":""},
{"proj":"GT Miami","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Michael McLane","start":"2023-06","end":"2027-01","pct":10,"note":""},
{"proj":"GT Miami","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Mandy Chen","start":"2024-06","end":"2027-01","pct":25,"note":""},
{"proj":"GT Miami","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Luke Borden","start":"2024-06","end":"2027-01","pct":40,"note":""},
{"proj":"GT Ft. Lauderale","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Michael McLane","start":"2025-07","end":"2027-03","pct":10,"note":""},
{"proj":"GT Ft. Lauderale","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Mandy Chen","start":"2025-07","end":"2027-03","pct":25,"note":""},
{"proj":"GT Ft. Lauderale","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Luke Borden","start":"2025-07","end":"2027-03","pct":40,"note":""},
{"proj":"GT Tallahassee","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Luke Borden","start":"2025-07","end":"2026-12","pct":20,"note":""},
{"proj":"GT Tallahassee","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Mandy Chen","start":"2025-07","end":"2026-12","pct":10,"note":""},
{"proj":"GT Houston","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Alicia Cargo","start":"2026-01","end":"2026-12","pct":25,"note":"1/2 floor, lease not yet signed, will be in construction early Q4 if GT signs lease"},
{"proj":"GT Houston","status":"Pursuit","type":"Opportunity","client":"Greenberg Traurig","person":"[NEW HIRE] Izzy Vollbrecht","start":"2026-07","end":"2026-12","pct":10,"note":""},
{"proj":"GT SLC","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Naida Serak","start":"2025-08","end":"2026-07","pct":30,"note":""},
{"proj":"GT SLC","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Amelia Mayberry","start":"2025-08","end":"2026-07","pct":30,"note":"Leave as of July 2026"},
{"proj":"GT SLC","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Alex He","start":"2025-08","end":"2026-07","pct":20,"note":""},
{"proj":"GT LA","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Amelia Mayberry","start":"2026-03","end":"2028-03","pct":30,"note":"Leave as of July 2026"},
{"proj":"GT LA","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Naida Serak","start":"2026-06","end":"2028-03","pct":30,"note":""},
{"proj":"GT LA","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Alex He","start":"2026-03","end":"2028-03","pct":20,"note":""},
{"proj":"GT LA","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Jennylee Nguyen","start":"2026-06","end":"2028-03","pct":25,"note":""},
{"proj":"GT San Diego","status":"Pursuit","type":"Opportunity","client":"Greenberg Traurig","person":"Amelia Mayberry","start":"2026-04","end":"2026-07","pct":25,"note":"Leave as of July 2026"},
{"proj":"GT San Diego","status":"Pursuit","type":"Opportunity","client":"Greenberg Traurig","person":"Naida Serak","start":"2026-07","end":"2027-05","pct":25,"note":"when amelia on leave"},
{"proj":"GT San Diego","status":"Pursuit","type":"Opportunity","client":"Greenberg Traurig","person":"Alex He","start":"2026-04","end":"2027-05","pct":25,"note":""},
{"proj":"GT San Diego","status":"Pursuit","type":"Opportunity","client":"Greenberg Traurig","person":"[NEW HIRE] Izzy Vollbrecht","start":"2026-07","end":"2027-05","pct":25,"note":""},
{"proj":"GT Albany","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Michael McLane","start":"2026-04","end":"2027-02","pct":10,"note":""},
{"proj":"GT Albany","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Alicia Cargo","start":"2026-04","end":"2027-02","pct":10,"note":"TBD on if light touch bc LL builds spec suite at new building (current being bought) or full build if no agreement)."},
{"proj":"GT Albany","status":"Pursuit","type":"Opportunity","client":"Greenberg Traurig","person":"[NEW HIRE] Izzy Vollbrecht","start":"2026-07","end":"2027-02","pct":10,"note":""},
{"proj":"GT OVA","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Michael McLane","start":"2026-04","end":"2027-04","pct":10,"note":""},
{"proj":"GT OVA","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Zac Sargent","start":"2026-04","end":"2027-04","pct":20,"note":""},
{"proj":"GT OVA","status":"Pursuit","type":"Opportunity","client":"Greenberg Traurig","person":"[NEW HIRE] Izzy Vollbrecht","start":"2026-07","end":"2027-04","pct":25,"note":""},
{"proj":"GT PMO","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Alex He","start":"2025-03","end":"2026-12","pct":20,"note":""},
{"proj":"GT PMO","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Michael McLane","start":"2025-07","end":"2026-12","pct":10,"note":""},
{"proj":"GT PMO","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Naida Serak","start":"2025-07","end":"2026-12","pct":75,"note":""},
{"proj":"GT PMO","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Deb Greenfield","start":"2025-07","end":"2026-12","pct":10,"note":"PRO"},
{"proj":"GT PMO","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Dannah Seecoomar","start":"2025-07","end":"2026-07","pct":20,"note":"Nadine to backfill Dannah"},
{"proj":"GT PMO","status":"Pursuit","type":"Opportunity","client":"Greenberg Traurig","person":"Nadine Moussa","start":"2025-07","end":"2026-12","pct":20,"note":"Nadine to backfill Dannah"},
{"proj":"GT PMO","status":"Active","type":"Awarded","client":"Greenberg Traurig","person":"Alicia Cargo","start":"2025-12","end":"2026-12","pct":10,"note":""},
{"proj":"HARTING - pre-site selection DD","status":"Pursuit","type":"Opportunity","client":"HARTING","person":"Chris Scala","start":"2026-07","end":"2026-12","pct":25,"note":""},
{"proj":"Hogan Lovells CM","status":"Active","type":"Awarded","client":"Hogan Lovells","person":"Benay Josselson","start":"2026-01","end":"2026-12","pct":20,"note":""},
{"proj":"JetZero","status":"Active","type":"Awarded","client":"JetZero","person":"Emily Sobel","start":"2025-09","end":"2030-12","pct":15,"note":""},
{"proj":"JetZero","status":"Active","type":"Awarded","client":"JetZero","person":"Chris Scala","start":"2025-09","end":"2030-12","pct":35,"note":""},
{"proj":"JetZero","status":"Active","type":"Awarded","client":"JetZero","person":"Jessica Jeffrey","start":"2025-09","end":"2030-12","pct":100,"note":""},
{"proj":"JetZero","status":"Active","type":"Awarded","client":"JetZero","person":"Liza Horstman","start":"2025-09","end":"2028-12","pct":100,"note":""},
{"proj":"JetZero","status":"Active","type":"Awarded","client":"JetZero","person":"Eno Chen","start":"2025-09","end":"2030-12","pct":100,"note":""},
{"proj":"JetZero","status":"Active","type":"Awarded","client":"JetZero","person":"Andrew Peters","start":"2026-01","end":"2026-12","pct":5,"note":""},
{"proj":"JetZero","status":"Active","type":"Awarded","client":"JetZero","person":"Rebekah Palmer","start":"2026-02","end":"2030-12","pct":50,"note":""},
{"proj":"JetZero","status":"Pursuit","type":"Opportunity","client":"JetZero","person":"[NEW HIRE] Ashlee Mejia","start":"2026-07","end":"2030-12","pct":50,"note":""},
{"proj":"JMAN","status":"Active","type":"Awarded","client":"JMAN","person":"Jay Khoury","start":"2026-03","end":"2026-07","pct":25,"note":""},
{"proj":"JMAN","status":"Active","type":"Awarded","client":"JMAN","person":"Anika Tsapatsaris","start":"2026-03","end":"2026-07","pct":15,"note":""},
{"proj":"JPMC - 383M","status":"Active","type":"Awarded","client":"JPMC","person":"Emily Sobel","start":"2025-04","end":"2027-12","pct":25,"note":""},
{"proj":"JPMC - 383M","status":"Active","type":"Awarded","client":"JPMC","person":"Lacey Schwartz","start":"2024-11","end":"2027-12","pct":100,"note":""},
{"proj":"JPMC - 383M","status":"Active","type":"Awarded","client":"JPMC","person":"Sabrina Jones","start":"2026-01","end":"2027-12","pct":50,"note":""},
{"proj":"JPMC - 383M","status":"Active","type":"Awarded","client":"JPMC","person":"Triana Carter","start":"2026-06","end":"2027-12","pct":50,"note":""},
{"proj":"JPMC - 383M","status":"Active","type":"Awarded","client":"JPMC","person":"Rachel Haberman","start":"2026-02","end":"2027-12","pct":50,"note":""},
{"proj":"JPMC - 270P","status":"Active","type":"Awarded","client":"JPMC","person":"Kathy Spiegel","start":"2026-02","end":"2026-12","pct":100,"note":""},
{"proj":"JPMC - 270P","status":"Active","type":"Awarded","client":"JPMC","person":"Artie Benoit","start":"2026-02","end":"2026-12","pct":100,"note":""},
{"proj":"JPMC - 270P","status":"Active","type":"Awarded","client":"JPMC","person":"Alli Hochberg","start":"2026-02","end":"2026-06","pct":50,"note":"Leave as of July 2026"},
{"proj":"JPMC - 270P","status":"Active","type":"Awarded","client":"JPMC","person":"Amanda Hirsh","start":"2026-02","end":"2026-12","pct":50,"note":""},
{"proj":"JPMC - 270P","status":"Active","type":"Awarded","client":"JPMC","person":"Sarah Alim","start":"2026-02","end":"2026-12","pct":100,"note":""},
{"proj":"JPMC - 270P","status":"Active","type":"Awarded","client":"JPMC","person":"Sabrina Jones","start":"2026-02","end":"2026-12","pct":50,"note":"Ari to free up Sabrina?"},
{"proj":"JPMC - 270P","status":"Pursuit","type":"Opportunity","client":"JPMC","person":"Ariel Levin","start":"2026-07","end":"2026-12","pct":50,"note":"Ari to free up Sabrina?"},
{"proj":"JPMC - 270P","status":"Active","type":"Awarded","client":"JPMC","person":"Timothy Carey","start":"2026-04","end":"2026-12","pct":50,"note":""},
{"proj":"JPMC - 270P","status":"Active","type":"Awarded","client":"JPMC","person":"Triana Carter","start":"2026-06","end":"2026-12","pct":50,"note":""},
{"proj":"JPMC - 270P","status":"Active","type":"Awarded","client":"JPMC","person":"Jay Khoury","start":"2026-04","end":"2026-12","pct":50,"note":""},
{"proj":"JPMC SW - Core5","status":"Active","type":"Awarded","client":"JPMC","person":"Brianna King","start":"2025-09","end":"2026-12","pct":100,"note":""},
{"proj":"JPMC SW - Core5","status":"Active","type":"Awarded","client":"JPMC","person":"Ben Rubin","start":"2025-09","end":"2026-12","pct":75,"note":""},
{"proj":"JPMC SW - Core5","status":"Active","type":"Awarded","client":"JPMC","person":"Marc Messina","start":"2025-09","end":"2026-12","pct":75,"note":""},
{"proj":"JPMC SW - Core5","status":"Active","type":"Awarded","client":"JPMC","person":"Jess White","start":"2025-09","end":"2026-12","pct":10,"note":""},
{"proj":"JPMC SW - Core5","status":"Active","type":"Awarded","client":"JPMC","person":"Jess Marman","start":"2026-01","end":"2026-12","pct":50,"note":"100% of Jess's allocation"},
{"proj":"JPMC SW - Core5","status":"Active","type":"Awarded","client":"JPMC","person":"Brendan Hughes","start":"2025-12","end":"2026-12","pct":50,"note":""},
{"proj":"JPMC SW - Core5","status":"Active","type":"Awarded","client":"JPMC","person":"Mandy Chen","start":"2026-01","end":"2026-12","pct":100,"note":""},
{"proj":"JPMC SW - Core5","status":"Active","type":"Awarded","client":"JPMC","person":"Emily Glatt","start":"2026-02","end":"2026-12","pct":25,"note":""},
{"proj":"JPMC SW - Core5","status":"Active","type":"Awarded","client":"JPMC","person":"David Humphrey","start":"2026-02","end":"2026-12","pct":75,"note":""},
{"proj":"JPMC SW - Core5","status":"Active","type":"Awarded","client":"JPMC","person":"Deb Greenfield","start":"2025-10","end":"2026-12","pct":50,"note":""},
{"proj":"JPMC SW - HUB","status":"Active","type":"Awarded","client":"JPMC","person":"Saphira Chery","start":"2026-04","end":"2026-12","pct":100,"note":""},
{"proj":"JPMC SW - HUB","status":"Pursuit","type":"Opportunity","client":"JPMC","person":"[NEW HIRE] Julia Florkowski","start":"2026-07","end":"2026-12","pct":100,"note":"NYC HUB Lead"},
{"proj":"JPMC SW - HUB","status":"Active","type":"Awarded","client":"JPMC","person":"Ginger Gilden","start":"2026-06","end":"2026-12","pct":100,"note":"Shift focus to Pantry Program"},
{"proj":"JPMC SW - HUB","status":"Active","type":"Awarded","client":"JPMC","person":"Chris Hocker","start":"2026-02","end":"2026-12","pct":100,"note":"Deleware HUB"},
{"proj":"JPMC SW - HUB","status":"Active","type":"Awarded","client":"JPMC","person":"Tasia Long","start":"2026-01","end":"2026-12","pct":100,"note":"Chicago HUB.  End date dependent on transition of Midwest to Florida"},
{"proj":"JPMC SW - HUB","status":"Active","type":"Awarded","client":"JPMC","person":"[NEW HIRE] Danica Woo","start":"2026-07","end":"2026-12","pct":100,"note":"Tampa HUB lead"},
{"proj":"JPMC Deleware FF&E","status":"Pursuit","type":"Opportunity","client":"JPMC","person":"Amanda Hirsh","start":"2026-06","end":"2026-12","pct":50,"note":""},
{"proj":"JPMC Deleware FF&E","status":"Pursuit","type":"Opportunity","client":"JPMC","person":"Jay Khoury","start":"2026-06","end":"2026-12","pct":50,"note":""},
{"proj":"JPMC Deleware FF&E","status":"Pursuit","type":"Opportunity","client":"JPMC","person":"Deb Greenfield","start":"2026-07","end":"2026-12","pct":25,"note":"Is Deb a good fit?"},
{"proj":"Lazard - 30 Rock D&C","status":"Active","type":"Awarded","client":"Lazard","person":"Marc Messina","start":"2026-05","end":"2026-11","pct":25,"note":""},
{"proj":"Lazard - 30 Rock D&C","status":"Active","type":"Awarded","client":"Lazard","person":"Jess White","start":"2026-05","end":"2026-06","pct":25,"note":"A/E RFPs"},
{"proj":"Lazard - 30 Rock D&C","status":"Active","type":"Awarded","client":"Lazard","person":"Ariel Levin","start":"2026-05","end":"2026-06","pct":25,"note":"A/E bid leveling"},
{"proj":"Lazard - 30 Rock D&C","status":"Active","type":"Awarded","client":"Lazard","person":"[NEW HIRE] Izzy Vollbrecht","start":"2026-07","end":"2026-11","pct":25,"note":"MG to weigh-in"},
{"proj":"Lazard - Change Mgmt (Phase 2)","status":"Active","type":"Awarded","client":"Lazard","person":"Benay Josselson","start":"2026-05","end":"2026-11","pct":40,"note":""},
{"proj":"Lazard - Change Mgmt (Phase 2)","status":"Active","type":"Awarded","client":"Lazard","person":"Bailey Graves","start":"2026-05","end":"2026-11","pct":30,"note":""},
{"proj":"Lazard - Change Mgmt (Phase 2)","status":"Active","type":"Awarded","client":"Lazard","person":"Ashley Conroy","start":"2026-05","end":"2026-11","pct":30,"note":""},
{"proj":"Lazard - Change Mgmt (Phase 2)","status":"Active","type":"Awarded","client":"Lazard","person":"Karenna Laufer","start":"2026-05","end":"2026-11","pct":25,"note":""},
{"proj":"Macro Legal - NDAs, T&Cs","status":"Active","type":"Awarded","client":"Macro Internal","person":"Ben Rubin","start":"2024-09","end":"2026-12","pct":10,"note":""},
{"proj":"Macro Legal - NDAs, T&Cs","status":"Active","type":"Awarded","client":"Macro Internal","person":"Jess White","start":"2024-09","end":"2026-12","pct":10,"note":""},
{"proj":"Macro Legal - Salesforce Intake","status":"Active","type":"Awarded","client":"Macro Internal","person":"Deb Greenfield","start":"2024-09","end":"2026-12","pct":20,"note":""},
{"proj":"Macro - Marketing","status":"Active","type":"Awarded","client":"Macro Internal","person":"Neal Wellington","start":"2025-01","end":"2025-12","pct":100,"note":""},
{"proj":"MDC - 9250","status":"Pursuit","type":"Opportunity","client":"MDC","person":"Michael McLane","start":"2026-06","end":"2027-06","pct":50,"note":""},
{"proj":"MDC - 9250","status":"Pursuit","type":"Opportunity","client":"MDC","person":"Chris Scala","start":"2026-06","end":"2027-06","pct":25,"note":""},
{"proj":"MDC - 9250","status":"Pursuit","type":"Opportunity","client":"MDC","person":"Nadine Moussa","start":"2026-06","end":"2027-06","pct":50,"note":""},
{"proj":"MDC - 9250","status":"Pursuit","type":"Opportunity","client":"MDC","person":"Beatriz dePaulis","start":"2026-06","end":"2027-06","pct":100,"note":"Pending project (re)approval, or redeploy as of 6/15"},
{"proj":"MTSI - Huntsville","status":"Active","type":"Awarded","client":"MTSI","person":"Kathryn Martinez","start":"2025-10","end":"2026-12","pct":20,"note":""},
{"proj":"MTSI - Huntsville","status":"Active","type":"Awarded","client":"MTSI","person":"Amelia Mayberry","start":"2025-10","end":"2026-06","pct":40,"note":"Leave as of July 2026"},
{"proj":"MTSI - Huntsville","status":"Active","type":"Awarded","client":"MTSI","person":"[NEW HIRE] Fernando (DMV Hire)","start":"2026-08","end":"2026-12","pct":40,"note":""},
{"proj":"MTSI - Huntsville","status":"Active","type":"Awarded","client":"MTSI","person":"Tom Bucciaglia","start":"2026-01","end":"2026-06","pct":20,"note":"Increase after M&N closeout in June"},
{"proj":"MTSI - Huntsville","status":"Pursuit","type":"Opportunity","client":"MTSI","person":"Tom Bucciaglia","start":"2026-07","end":"2026-12","pct":40,"note":"Increase after M&N closeout in June"},
{"proj":"MTSI - Lorton, VA","status":"Active","type":"Awarded","client":"MTSI","person":"Kathryn Martinez","start":"2025-11","end":"2026-08","pct":25,"note":""},
{"proj":"MTSI - Lorton, VA","status":"Active","type":"Awarded","client":"MTSI","person":"Tom Bucciaglia","start":"2025-11","end":"2026-08","pct":40,"note":""},
{"proj":"MTSI - Alexandria HQ","status":"Active","type":"Awarded","client":"MTSI","person":"Kathryn Martinez","start":"2026-04","end":"2026-12","pct":25,"note":""},
{"proj":"MTSI - Alexandria HQ","status":"Active","type":"Awarded","client":"MTSI","person":"Jonathan Stukalin","start":"2026-04","end":"2026-12","pct":35,"note":""},
{"proj":"MTSI - Alexandria HQ","status":"Active","type":"Awarded","client":"MTSI","person":"Vicky Vidal","start":"2026-04","end":"2026-12","pct":40,"note":""},
{"proj":"MTSI - Alexandria SCIF","status":"Pursuit","type":"Opportunity","client":"MTSI","person":"Kathryn Martinez","start":"2026-06","end":"2026-12","pct":20,"note":""},
{"proj":"MTSI - Alexandria SCIF","status":"Pursuit","type":"Opportunity","client":"MTSI","person":"[NEW HIRE] Fernando (DMV Hire)","start":"2026-08","end":"2026-12","pct":35,"note":""},
{"proj":"MTSI - Niceville","status":"Pursuit","type":"Opportunity","client":"MTSI","person":"Kathryn Martinez","start":"2026-06","end":"2026-12","pct":20,"note":""},
{"proj":"MTSI - Niceville","status":"Pursuit","type":"Opportunity","client":"MTSI","person":"[NEW HIRE] Fernando (DMV Hire)","start":"2026-08","end":"2026-12","pct":35,"note":"Other DMV hire potential projects: GT WDC, Lorton new project (50% pursuit), and Dayton"},
{"proj":"MTSI - Dayton","status":"Pursuit","type":"Opportunity","client":"MTSI","person":"Kathryn Martinez","start":"2026-07","end":"2027-11","pct":20,"note":""},
{"proj":"MTSI - Dayton","status":"Pursuit","type":"Opportunity","client":"MTSI","person":"Alicia Cargo","start":"2026-07","end":"2027-11","pct":30,"note":"Need to free Alicia up from Fanatics Portland in order to make this happen"},
{"proj":"NBA Change Mgmt","status":"Active","type":"Awarded","client":"NBA","person":"Benay Josselson","start":"2026-05","end":"2026-08","pct":35,"note":""},
{"proj":"NBA Change Mgmt","status":"Active","type":"Awarded","client":"NBA","person":"Karenna Laufer","start":"2026-05","end":"2026-08","pct":30,"note":""},
{"proj":"NBA Change Mgmt","status":"Active","type":"Awarded","client":"NBA","person":"Rachel Haberman","start":"2026-06","end":"2026-08","pct":25,"note":""},
{"proj":"NYCLU - Relo to 100 Church","status":"Active","type":"Awarded","client":"NYCLU","person":"Fred Buscaglia","start":"2026-04","end":"2026-12","pct":10,"note":""},
{"proj":"NYCLU - Relo to 100 Church","status":"Active","type":"Awarded","client":"NYCLU","person":"Victoria Verdan","start":"2026-04","end":"2026-12","pct":35,"note":""},
{"proj":"NYU 3MTC","status":"Active","type":"Awarded","client":"NYU","person":"Andrew Peters","start":"2026-04","end":"2028-06","pct":25,"note":""},
{"proj":"NYU 3MTC","status":"Active","type":"Awarded","client":"NYU","person":"Timothy Carey","start":"2026-04","end":"2028-06","pct":25,"note":""},
{"proj":"NYU 3MTC","status":"Active","type":"Awarded","client":"NYU","person":"Chris Scala","start":"2026-04","end":"2028-06","pct":15,"note":""},
{"proj":"NYU 3MTC","status":"Pursuit","type":"Opportunity","client":"NYU","person":"[NEW HIRE] Cost Manager","start":"2026-07","end":"2028-06","pct":20,"note":""},
{"proj":"SEIA - NOVA","status":"Active","type":"Awarded","client":"SEIA","person":"Michael McLane","start":"2026-05","end":"2026-12","pct":10,"note":""},
{"proj":"SEIA - NOVA","status":"Active","type":"Awarded","client":"SEIA","person":"Zac Sargent","start":"2026-05","end":"2026-12","pct":20,"note":""},
{"proj":"Sumitomo Change Management","status":"Pursuit","type":"Opportunity","client":"Sumitomo","person":"Benay Josselson","start":"2026-08","end":"2026-10","pct":30,"note":""},
{"proj":"Sumitomo Change Management","status":"Pursuit","type":"Opportunity","client":"Sumitomo","person":"Karenna Laufer","start":"2026-08","end":"2026-10","pct":20,"note":""},
{"proj":"Sumitomo Change Management","status":"Pursuit","type":"Opportunity","client":"Sumitomo","person":"Ashley Conroy","start":"2026-08","end":"2026-10","pct":30,"note":""},
{"proj":"TIAA - Staff Aug","status":"Active","type":"Awarded","client":"TIAA","person":"Nora Hasan","start":"2025-08","end":"2026-07","pct":100,"note":"TIAA may hire as of August 2026"},
{"proj":"TIAA - Cost Consultancy","status":"Active","type":"Awarded","client":"TIAA","person":"Andrew Peters","start":"2026-02","end":"2026-12","pct":25,"note":""},
{"proj":"TIAA - Cost Consultancy","status":"Active","type":"Awarded","client":"TIAA","person":"Timothy Carey","start":"2026-02","end":"2026-12","pct":50,"note":""},
{"proj":"TIAA - Capital Planning PMO","status":"Active","type":"Awarded","client":"TIAA","person":"Marc Messina","start":"2026-04","end":"2026-12","pct":10,"note":""},
{"proj":"TIAA - Capital Planning PMO","status":"Active","type":"Awarded","client":"TIAA","person":"Ben Rubin","start":"2026-04","end":"2026-12","pct":50,"note":""},
{"proj":"TIAA - Capital Planning PMO","status":"Active","type":"Awarded","client":"TIAA","person":"Maria Hadim","start":"2026-04","end":"2026-06","pct":75,"note":"TBD timing to transition off, for discussion with Marc/Ben after late June steerco"},
{"proj":"TIAA - Capital Planning PMO","status":"Active","type":"Awarded","client":"TIAA","person":"Rodney Stallworth","start":"2026-04","end":"2026-12","pct":75,"note":""},
{"proj":"Wharton SF","status":"Pursuit","type":"Opportunity","client":"UPENN","person":"Kathryn Martinez","start":"2026-05","end":"2027-12","pct":10,"note":""},
{"proj":"Wharton SF","status":"Pursuit","type":"Opportunity","client":"UPENN","person":"Jennylee Nguyen","start":"2026-06","end":"2027-12","pct":50,"note":""},
{"proj":"Wharton SF","status":"Pursuit","type":"Opportunity","client":"UPENN","person":"[NEW HIRE] Alex Bluvol","start":"2026-07","end":"2027-12","pct":50,"note":""},
{"proj":"Wharton SF","status":"Pursuit","type":"Opportunity","client":"UPENN","person":"[NEW HIRE] Cost Manager","start":"2026-07","end":"2027-12","pct":20,"note":""},
{"proj":"Wharton SF","status":"Pursuit","type":"Opportunity","client":"UPENN","person":"Andrew Peters","start":"2026-05","end":"2027-12","pct":20,"note":""},
{"proj":"Wharton SF","status":"Pursuit","type":"Opportunity","client":"UPENN","person":"Kristen Raymond","start":"2026-05","end":"2027-12","pct":50,"note":""},
{"proj":"Withers Change Mgmt","status":"Active","type":"Awarded","client":"Withers","person":"Ashley Conroy","start":"2026-02","end":"2026-06","pct":25,"note":""},
{"proj":"Withers Change Mgmt","status":"Active","type":"Awarded","client":"Withers","person":"Karenna Laufer","start":"2026-02","end":"2026-06","pct":25,"note":""},
{"proj":"Withers Change Mgmt","status":"Active","type":"Awarded","client":"Withers","person":"Benay Josselson","start":"2026-02","end":"2026-06","pct":10,"note":""},
{"proj":"WTW NYC","status":"Active","type":"Awarded","client":"WTW","person":"Joe Guarnieri","start":"2025-11","end":"2026-07","pct":50,"note":""},
{"proj":"WTW NYC","status":"Pursuit","type":"Opportunity","client":"WTW","person":"[NEW HIRE] Ashlee Mejia","start":"2026-07","end":"2026-07","pct":50,"note":"Backfill Nadine on WTW NYC, Nadine to GT PMO"},
{"proj":"WTW NYC","status":"Active","type":"Awarded","client":"WTW","person":"Nadine Moussa","start":"2025-11","end":"2026-07","pct":50,"note":"Backfill Nadine on WTW NYC, Nadine to GT PMO"},
{"proj":"Yusen Change Mgmt","status":"Active","type":"Awarded","client":"Yusen","person":"Ashley Conroy","start":"2026-04","end":"2026-10","pct":25,"note":""},
{"proj":"Yusen Change Mgmt","status":"Active","type":"Awarded","client":"Yusen","person":"Karenna Laufer","start":"2026-04","end":"2026-10","pct":25,"note":""},
{"proj":"Yusen Change Mgmt","status":"Active","type":"Awarded","client":"Yusen","person":"Benay Josselson","start":"2026-04","end":"2026-10","pct":40,"note":""},
{"proj":"YearUp","status":"Active","type":"Awarded","client":"YearUp","person":"Zac Sargent","start":"2025-11","end":"2026-12","pct":20,"note":""}
];
